export const DEFAULT_FILAMENT_TYPES = [
  "PLA",
  "PLA+",
  "Silk PLA",
  "Tough PLA",
  "Matte PLA",
  "PETG",
  "ABS",
  "ASA",
  "Nylon (PA6)",
  "Nylon (PA12)",
  "PC (Polycarbonate)",
  "TPU",
  "TPE",
  "HIPS",
  "PVA",
  "Carbon Fiber PLA (PLA-CF)",
  "Carbon Fiber PETG (PETG-CF)",
  "Carbon Fiber Nylon (PA-CF)",
  "Glass Fiber Nylon (PA-GF)",
  "Wood PLA",
  "Metal PLA",
  "Glow-in-the-Dark PLA",
  "PC-ABS",
  "PCTG",
  "PP (Polypropylene)",
  "PEEK",
  "PEI (Ultem)",
];
